// Package webpush sends RFC 8030 Web Push messages to browser endpoints.
package webpush

import "context"

// Config holds VAPID credentials. Keys are base64url-encoded, as generated by
// `make vapid-keys`; deployed environments read the private key from SSM.
type Config struct {
	PublicKey  string
	PrivateKey string
	// Subject is the VAPID "sub" claim: a mailto: or https: URL push services
	// use to contact the sender about delivery problems.
	Subject string
	// TTLSeconds is how long a push service may hold an undelivered message.
	TTLSeconds int
}

// Subscription is the destination of a single push: the endpoint URL plus the
// browser-generated keys that encrypt the payload for it.
type Subscription struct {
	Endpoint string
	P256dh   string
	Auth     string
}

// Gateway sends one encrypted push message.
type Gateway interface {
	// Send delivers payload to sub. The returned error is ErrSubscriptionGone
	// when the push service reports the endpoint is permanently unusable.
	Send(ctx context.Context, sub Subscription, payload []byte) error
	// PublicKey returns the VAPID application server key browsers must pass to
	// PushManager.subscribe(). Empty when push is not configured.
	PublicKey() string
}
