// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/coupon.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/coupon.go -destination=internal/mocks/coupon_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/handloom/admin/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCouponRepository is a mock of CouponRepository interface.
type MockCouponRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCouponRepositoryMockRecorder
	isgomock struct{}
}

// MockCouponRepositoryMockRecorder is the mock recorder for MockCouponRepository.
type MockCouponRepositoryMockRecorder struct {
	mock *MockCouponRepository
}

// NewMockCouponRepository creates a new mock instance.
func NewMockCouponRepository(ctrl *gomock.Controller) *MockCouponRepository {
	mock := &MockCouponRepository{ctrl: ctrl}
	mock.recorder = &MockCouponRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCouponRepository) EXPECT() *MockCouponRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCouponRepository) Create(ctx context.Context, coupon *domain.Coupon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, coupon)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCouponRepositoryMockRecorder) Create(ctx, coupon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCouponRepository)(nil).Create), ctx, coupon)
}

// Delete mocks base method.
func (m *MockCouponRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCouponRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCouponRepository)(nil).Delete), ctx, id)
}

// GetByCode mocks base method.
func (m *MockCouponRepository) GetByCode(ctx context.Context, code string) (*domain.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*domain.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockCouponRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockCouponRepository)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockCouponRepository) GetByID(ctx context.Context, id string) (*domain.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCouponRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCouponRepository)(nil).GetByID), ctx, id)
}

// GetCustomerUsage mocks base method.
func (m *MockCouponRepository) GetCustomerUsage(ctx context.Context, customerID, couponID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerUsage", ctx, customerID, couponID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerUsage indicates an expected call of GetCustomerUsage.
func (mr *MockCouponRepositoryMockRecorder) GetCustomerUsage(ctx, customerID, couponID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerUsage", reflect.TypeOf((*MockCouponRepository)(nil).GetCustomerUsage), ctx, customerID, couponID)
}

// IncrementCustomerUsage mocks base method.
func (m *MockCouponRepository) IncrementCustomerUsage(ctx context.Context, customerID, couponID string, limit int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementCustomerUsage", ctx, customerID, couponID, limit)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementCustomerUsage indicates an expected call of IncrementCustomerUsage.
func (mr *MockCouponRepositoryMockRecorder) IncrementCustomerUsage(ctx, customerID, couponID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCustomerUsage", reflect.TypeOf((*MockCouponRepository)(nil).IncrementCustomerUsage), ctx, customerID, couponID, limit)
}

// IncrementUsage mocks base method.
func (m *MockCouponRepository) IncrementUsage(ctx context.Context, couponID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementUsage", ctx, couponID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementUsage indicates an expected call of IncrementUsage.
func (mr *MockCouponRepositoryMockRecorder) IncrementUsage(ctx, couponID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementUsage", reflect.TypeOf((*MockCouponRepository)(nil).IncrementUsage), ctx, couponID)
}

// List mocks base method.
func (m *MockCouponRepository) List(ctx context.Context, req domain.ListCouponsRequest) (*domain.ListCouponsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].(*domain.ListCouponsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCouponRepositoryMockRecorder) List(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCouponRepository)(nil).List), ctx, req)
}

// ListPublic mocks base method.
func (m *MockCouponRepository) ListPublic(ctx context.Context) ([]*domain.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublic", ctx)
	ret0, _ := ret[0].([]*domain.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublic indicates an expected call of ListPublic.
func (mr *MockCouponRepositoryMockRecorder) ListPublic(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublic", reflect.TypeOf((*MockCouponRepository)(nil).ListPublic), ctx)
}

// RecordUsage mocks base method.
func (m *MockCouponRepository) RecordUsage(ctx context.Context, usage *domain.CouponUsage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordUsage", ctx, usage)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordUsage indicates an expected call of RecordUsage.
func (mr *MockCouponRepositoryMockRecorder) RecordUsage(ctx, usage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordUsage", reflect.TypeOf((*MockCouponRepository)(nil).RecordUsage), ctx, usage)
}

// Update mocks base method.
func (m *MockCouponRepository) Update(ctx context.Context, coupon *domain.Coupon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, coupon)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCouponRepositoryMockRecorder) Update(ctx, coupon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCouponRepository)(nil).Update), ctx, coupon)
}

// MockCouponService is a mock of CouponService interface.
type MockCouponService struct {
	ctrl     *gomock.Controller
	recorder *MockCouponServiceMockRecorder
	isgomock struct{}
}

// MockCouponServiceMockRecorder is the mock recorder for MockCouponService.
type MockCouponServiceMockRecorder struct {
	mock *MockCouponService
}

// NewMockCouponService creates a new mock instance.
func NewMockCouponService(ctrl *gomock.Controller) *MockCouponService {
	mock := &MockCouponService{ctrl: ctrl}
	mock.recorder = &MockCouponServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCouponService) EXPECT() *MockCouponServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCouponService) Create(ctx context.Context, req domain.CreateCouponRequest, createdBy string) (*domain.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req, createdBy)
	ret0, _ := ret[0].(*domain.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCouponServiceMockRecorder) Create(ctx, req, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCouponService)(nil).Create), ctx, req, createdBy)
}

// Delete mocks base method.
func (m *MockCouponService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCouponServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCouponService)(nil).Delete), ctx, id)
}

// GetByCode mocks base method.
func (m *MockCouponService) GetByCode(ctx context.Context, code string) (*domain.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*domain.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockCouponServiceMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockCouponService)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockCouponService) GetByID(ctx context.Context, id string) (*domain.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCouponServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCouponService)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockCouponService) List(ctx context.Context, req domain.ListCouponsRequest) (*domain.ListCouponsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].(*domain.ListCouponsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCouponServiceMockRecorder) List(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCouponService)(nil).List), ctx, req)
}

// Redeem mocks base method.
func (m *MockCouponService) Redeem(ctx context.Context, couponID, orderID, customerID string, discount int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Redeem", ctx, couponID, orderID, customerID, discount)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Redeem indicates an expected call of Redeem.
func (mr *MockCouponServiceMockRecorder) Redeem(ctx, couponID, orderID, customerID, discount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redeem", reflect.TypeOf((*MockCouponService)(nil).Redeem), ctx, couponID, orderID, customerID, discount)
}

// Update mocks base method.
func (m *MockCouponService) Update(ctx context.Context, id string, req domain.UpdateCouponRequest, updatedBy string) (*domain.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req, updatedBy)
	ret0, _ := ret[0].(*domain.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCouponServiceMockRecorder) Update(ctx, id, req, updatedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCouponService)(nil).Update), ctx, id, req, updatedBy)
}

// Validate mocks base method.
func (m *MockCouponService) Validate(ctx context.Context, code string, cc domain.CouponContext) (*domain.CouponValidationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, code, cc)
	ret0, _ := ret[0].(*domain.CouponValidationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockCouponServiceMockRecorder) Validate(ctx, code, cc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockCouponService)(nil).Validate), ctx, code, cc)
}
