// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/handloom/admin/internal/config"
	"github.com/handloom/admin/internal/embedder"
	"github.com/handloom/admin/internal/handler"
	"github.com/handloom/admin/internal/handler/store"
	"github.com/handloom/admin/internal/middleware"
	"github.com/handloom/admin/internal/worker/metrics"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Injectors from wire.go:

// InitializeAuthDeps creates Auth Lambda dependencies
func InitializeAuthDeps(ctx context.Context, cfg *config.Config) (*AuthDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	userService := ProvideUserService(userRepository, tokenStore)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	authHandler := ProvideAuthHandler(authService, userService, validation)
	auth := ProvideAuthMiddleware(authService)
	authDeps := &AuthDeps{
		Config:         cfg,
		Handler:        authHandler,
		AuthMiddleware: auth,
	}
	return authDeps, nil
}

// InitializeUserDeps creates User Lambda dependencies
func InitializeUserDeps(ctx context.Context, cfg *config.Config) (*UserDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	userService := ProvideUserService(userRepository, tokenStore)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	userHandler := ProvideUserHandler(userService, validation)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	userDeps := &UserDeps{
		Config:         cfg,
		Handler:        userHandler,
		AuthMiddleware: auth,
	}
	return userDeps, nil
}

// InitializeCatalogDeps creates Catalog Lambda dependencies
func InitializeCatalogDeps(ctx context.Context, cfg *config.Config) (*CatalogDeps, error) {
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	categoryRepository := ProvideCategoryRepository(pool)
	productRepository := ProvideProductRepository(pool)
	s3Client, err := ProvideS3Client(ctx, cfg)
	if err != nil {
		return nil, err
	}
	lambdaClient, err := ProvideLambdaClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	assetService := ProvideAssetService(s3Client, lambdaClient, cfg)
	categoryService := ProvideCategoryService(categoryRepository, productRepository, assetService)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	categoryHandler := ProvideCategoryHandler(categoryService, validation)
	inventoryRepository := ProvideInventoryRepository(pool)
	client, err := ProvideEmbedderClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	productService := ProvideProductService(productRepository, categoryRepository, inventoryRepository, assetService, client)
	dynamodbClient, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(dynamodbClient)
	inventoryService := ProvideInventoryService(inventoryRepository, userRepository)
	productHandler := ProvideProductHandler(productService, inventoryService, validation)
	tokenStore := ProvideTokenStore(dynamodbClient)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	catalogDeps := &CatalogDeps{
		Config:          cfg,
		CategoryHandler: categoryHandler,
		ProductHandler:  productHandler,
		AuthMiddleware:  auth,
		EmbedderClient:  client,
	}
	return catalogDeps, nil
}

// InitializeOrderDeps creates Order Lambda dependencies
func InitializeOrderDeps(ctx context.Context, cfg *config.Config) (*OrderDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	orderRepository := ProvideOrderRepository(client)
	customerRepository := ProvideCustomerRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	productRepository := ProvideProductRepository(pool)
	inventoryRepository := ProvideInventoryRepository(pool)
	priceQuoteRepository := ProvidePriceQuoteRepository(client)
	paymentRepository := ProvidePaymentRepository(client)
	pricingRuleRepository := ProvidePricingRuleRepository(client)
	categoryRepository := ProvideCategoryRepository(pool)
	pricingService := ProvidePricingService(pricingRuleRepository, priceQuoteRepository, categoryRepository, productRepository, cfg)
	orderService := ProvideOrderService(orderRepository, customerRepository, productRepository, inventoryRepository, priceQuoteRepository, paymentRepository, pricingService)
	cartRepository := ProvideCartRepository(client)
	cartService := ProvideCartService(cartRepository, productRepository, inventoryRepository)
	gateway, err := ProvidePhonePeGateway(cfg)
	if err != nil {
		return nil, err
	}
	paymentService := ProvidePaymentService(paymentRepository, orderRepository, inventoryRepository, cartService, customerRepository, gateway)
	refundRepository := ProvideRefundRepository(client)
	userRepository := ProvideUserRepository(client)
	auditRepository := ProvideAuditRepository(client)
	auditService := ProvideAuditService(auditRepository)
	notificationRepository := ProvideNotificationRepository(client)
	notificationService := ProvideNotificationService(notificationRepository, userRepository)
	refundService := ProvideRefundService(refundRepository, orderRepository, paymentRepository, inventoryRepository, userRepository, auditService, notificationService, gateway)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	orderHandler := ProvideOrderHandler(orderService, paymentService, refundService, validation)
	customerService := ProvideCustomerService(customerRepository, orderRepository)
	customerHandler := ProvideCustomerHandler(customerService, validation)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	orderDeps := &OrderDeps{
		Config:          cfg,
		OrderHandler:    orderHandler,
		CustomerHandler: customerHandler,
		AuthMiddleware:  auth,
	}
	return orderDeps, nil
}

// InitializePricingDeps creates Pricing Lambda dependencies
func InitializePricingDeps(ctx context.Context, cfg *config.Config) (*PricingDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	pricingRuleRepository := ProvidePricingRuleRepository(client)
	priceQuoteRepository := ProvidePriceQuoteRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	categoryRepository := ProvideCategoryRepository(pool)
	productRepository := ProvideProductRepository(pool)
	pricingService := ProvidePricingService(pricingRuleRepository, priceQuoteRepository, categoryRepository, productRepository, cfg)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	pricingHandler := ProvidePricingHandler(pricingService, validation)
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	pricingDeps := &PricingDeps{
		Config:         cfg,
		Handler:        pricingHandler,
		AuthMiddleware: auth,
	}
	return pricingDeps, nil
}

// InitializeInventoryDeps creates Inventory Lambda dependencies
func InitializeInventoryDeps(ctx context.Context, cfg *config.Config) (*InventoryDeps, error) {
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	inventoryRepository := ProvideInventoryRepository(pool)
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(client)
	inventoryService := ProvideInventoryService(inventoryRepository, userRepository)
	inventoryHandler := ProvideInventoryHandler(inventoryService)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	inventoryDeps := &InventoryDeps{
		Config:         cfg,
		Handler:        inventoryHandler,
		AuthMiddleware: auth,
	}
	return inventoryDeps, nil
}

// InitializeNotificationDeps creates Notification Lambda dependencies
func InitializeNotificationDeps(ctx context.Context, cfg *config.Config) (*NotificationDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	notificationRepository := ProvideNotificationRepository(client)
	userRepository := ProvideUserRepository(client)
	notificationService := ProvideNotificationService(notificationRepository, userRepository)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	notificationHandler := ProvideNotificationHandler(notificationService, validation)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	notificationDeps := &NotificationDeps{
		Config:         cfg,
		Handler:        notificationHandler,
		AuthMiddleware: auth,
	}
	return notificationDeps, nil
}

// InitializeCouponDeps creates Coupon Lambda dependencies
func InitializeCouponDeps(ctx context.Context, cfg *config.Config) (*CouponDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	couponRepository := ProvideCouponRepository(client)
	couponService := ProvideCouponService(couponRepository)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	couponHandler := ProvideCouponHandler(couponService, validation)
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	couponDeps := &CouponDeps{
		Config:         cfg,
		Handler:        couponHandler,
		AuthMiddleware: auth,
	}
	return couponDeps, nil
}

// InitializeAssetDeps creates Asset Lambda dependencies
func InitializeAssetDeps(ctx context.Context, cfg *config.Config) (*AssetDeps, error) {
	s3Client, err := ProvideS3Client(ctx, cfg)
	if err != nil {
		return nil, err
	}
	lambdaClient, err := ProvideLambdaClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	assetService := ProvideAssetService(s3Client, lambdaClient, cfg)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	assetHandler := ProvideAssetHandler(assetService, validation)
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	assetDeps := &AssetDeps{
		Config:         cfg,
		Handler:        assetHandler,
		AuthMiddleware: auth,
	}
	return assetDeps, nil
}

// InitializeReportDeps creates Report Lambda dependencies
func InitializeReportDeps(ctx context.Context, cfg *config.Config) (*ReportDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	reportRepository := ProvideReportRepository(client)
	orderRepository := ProvideOrderRepository(client)
	customerRepository := ProvideCustomerRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	productRepository := ProvideProductRepository(pool)
	inventoryRepository := ProvideInventoryRepository(pool)
	priceQuoteRepository := ProvidePriceQuoteRepository(client)
	paymentRepository := ProvidePaymentRepository(client)
	pricingRuleRepository := ProvidePricingRuleRepository(client)
	categoryRepository := ProvideCategoryRepository(pool)
	pricingService := ProvidePricingService(pricingRuleRepository, priceQuoteRepository, categoryRepository, productRepository, cfg)
	orderService := ProvideOrderService(orderRepository, customerRepository, productRepository, inventoryRepository, priceQuoteRepository, paymentRepository, pricingService)
	s3Client, err := ProvideS3Client(ctx, cfg)
	if err != nil {
		return nil, err
	}
	lambdaClient, err := ProvideLambdaClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	assetService := ProvideAssetService(s3Client, lambdaClient, cfg)
	embedderClient, err := ProvideEmbedderClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	productService := ProvideProductService(productRepository, categoryRepository, inventoryRepository, assetService, embedderClient)
	customerService := ProvideCustomerService(customerRepository, orderRepository)
	userRepository := ProvideUserRepository(client)
	inventoryService := ProvideInventoryService(inventoryRepository, userRepository)
	reportService := ProvideReportService(reportRepository, orderService, productService, customerService, inventoryService)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	reportHandler := ProvideReportHandler(reportService, validation)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	reportDeps := &ReportDeps{
		Config:         cfg,
		Handler:        reportHandler,
		AuthMiddleware: auth,
	}
	return reportDeps, nil
}

// InitializeAuditDeps creates Audit Lambda dependencies
func InitializeAuditDeps(ctx context.Context, cfg *config.Config) (*AuditDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	auditRepository := ProvideAuditRepository(client)
	auditService := ProvideAuditService(auditRepository)
	auditHandler := ProvideAuditHandler(auditService)
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	auditDeps := &AuditDeps{
		Config:         cfg,
		Handler:        auditHandler,
		AuthMiddleware: auth,
	}
	return auditDeps, nil
}

// InitializeStoreAuthDeps creates Store Auth Lambda dependencies
func InitializeStoreAuthDeps(ctx context.Context, cfg *config.Config) (*StoreAuthDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	otpRepository := ProvideOTPRepository(client)
	customerRepository := ProvideCustomerRepository(client)
	customerTokenStore := ProvideCustomerTokenStore(client)
	customerAuthService := ProvideCustomerAuthService(otpRepository, customerRepository, customerTokenStore, cfg)
	cartRepository := ProvideCartRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	productRepository := ProvideProductRepository(pool)
	inventoryRepository := ProvideInventoryRepository(pool)
	cartService := ProvideCartService(cartRepository, productRepository, inventoryRepository)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	authHandler := ProvideStoreAuthHandler(customerAuthService, cartService, validation)
	customerAuth := ProvideCustomerAuthMiddleware(customerAuthService)
	storeAuthDeps := &StoreAuthDeps{
		Config:                 cfg,
		Handler:                authHandler,
		CustomerAuthMiddleware: customerAuth,
	}
	return storeAuthDeps, nil
}

// InitializeStoreCatalogDeps creates Store Catalog Lambda dependencies
func InitializeStoreCatalogDeps(ctx context.Context, cfg *config.Config) (*StoreCatalogDeps, error) {
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	productRepository := ProvideProductRepository(pool)
	categoryRepository := ProvideCategoryRepository(pool)
	inventoryRepository := ProvideInventoryRepository(pool)
	s3Client, err := ProvideS3Client(ctx, cfg)
	if err != nil {
		return nil, err
	}
	lambdaClient, err := ProvideLambdaClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	assetService := ProvideAssetService(s3Client, lambdaClient, cfg)
	client, err := ProvideEmbedderClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	productService := ProvideProductService(productRepository, categoryRepository, inventoryRepository, assetService, client)
	categoryService := ProvideCategoryService(categoryRepository, productRepository, assetService)
	inventoryService := ProvideStoreInventoryService(inventoryRepository)
	catalogHandler := ProvideStoreCatalogHandler(productService, categoryService, inventoryService)
	storeCatalogDeps := &StoreCatalogDeps{
		Config:  cfg,
		Handler: catalogHandler,
	}
	return storeCatalogDeps, nil
}

// InitializeStoreCartDeps creates Store Cart Lambda dependencies
func InitializeStoreCartDeps(ctx context.Context, cfg *config.Config) (*StoreCartDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	cartRepository := ProvideCartRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	productRepository := ProvideProductRepository(pool)
	inventoryRepository := ProvideInventoryRepository(pool)
	cartService := ProvideCartService(cartRepository, productRepository, inventoryRepository)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	cartHandler := ProvideStoreCartHandler(cartService, validation)
	otpRepository := ProvideOTPRepository(client)
	customerRepository := ProvideCustomerRepository(client)
	customerTokenStore := ProvideCustomerTokenStore(client)
	customerAuthService := ProvideCustomerAuthService(otpRepository, customerRepository, customerTokenStore, cfg)
	optionalCartAuth := ProvideOptionalCartAuth(customerAuthService)
	storeCartDeps := &StoreCartDeps{
		Config:           cfg,
		Handler:          cartHandler,
		OptionalCartAuth: optionalCartAuth,
	}
	return storeCartDeps, nil
}

// InitializeStoreCheckoutDeps creates Store Checkout Lambda dependencies
func InitializeStoreCheckoutDeps(ctx context.Context, cfg *config.Config) (*StoreCheckoutDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	cartRepository := ProvideCartRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	productRepository := ProvideProductRepository(pool)
	inventoryRepository := ProvideInventoryRepository(pool)
	cartService := ProvideCartService(cartRepository, productRepository, inventoryRepository)
	orderRepository := ProvideOrderRepository(client)
	paymentRepository := ProvidePaymentRepository(client)
	customerRepository := ProvideCustomerRepository(client)
	gateway, err := ProvidePhonePeGateway(cfg)
	if err != nil {
		return nil, err
	}
	paymentService := ProvidePaymentService(paymentRepository, orderRepository, inventoryRepository, cartService, customerRepository, gateway)
	checkoutService := ProvideCheckoutService(cartService, orderRepository, paymentService, inventoryRepository, customerRepository)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	checkoutHandler := ProvideStoreCheckoutHandler(checkoutService, validation)
	otpRepository := ProvideOTPRepository(client)
	customerTokenStore := ProvideCustomerTokenStore(client)
	customerAuthService := ProvideCustomerAuthService(otpRepository, customerRepository, customerTokenStore, cfg)
	customerAuth := ProvideCustomerAuthMiddleware(customerAuthService)
	storeCheckoutDeps := &StoreCheckoutDeps{
		Config:                 cfg,
		Handler:                checkoutHandler,
		CustomerAuthMiddleware: customerAuth,
	}
	return storeCheckoutDeps, nil
}

// InitializeStoreOrdersDeps creates Store Orders Lambda dependencies
func InitializeStoreOrdersDeps(ctx context.Context, cfg *config.Config) (*StoreOrdersDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	orderRepository := ProvideOrderRepository(client)
	customerRepository := ProvideCustomerRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	productRepository := ProvideProductRepository(pool)
	inventoryRepository := ProvideInventoryRepository(pool)
	priceQuoteRepository := ProvidePriceQuoteRepository(client)
	paymentRepository := ProvidePaymentRepository(client)
	pricingRuleRepository := ProvidePricingRuleRepository(client)
	categoryRepository := ProvideCategoryRepository(pool)
	pricingService := ProvidePricingService(pricingRuleRepository, priceQuoteRepository, categoryRepository, productRepository, cfg)
	orderService := ProvideOrderService(orderRepository, customerRepository, productRepository, inventoryRepository, priceQuoteRepository, paymentRepository, pricingService)
	orderHandler := ProvideStoreOrderHandler(orderService, orderRepository)
	otpRepository := ProvideOTPRepository(client)
	customerTokenStore := ProvideCustomerTokenStore(client)
	customerAuthService := ProvideCustomerAuthService(otpRepository, customerRepository, customerTokenStore, cfg)
	customerAuth := ProvideCustomerAuthMiddleware(customerAuthService)
	storeOrdersDeps := &StoreOrdersDeps{
		Config:                 cfg,
		Handler:                orderHandler,
		CustomerAuthMiddleware: customerAuth,
	}
	return storeOrdersDeps, nil
}

// InitializeStoreTrackingDeps creates Store Tracking Lambda dependencies
func InitializeStoreTrackingDeps(ctx context.Context, cfg *config.Config) (*StoreTrackingDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	orderRepository := ProvideOrderRepository(client)
	shipmentRepository := ProvideShipmentRepository(client)
	trackingHandler := ProvideStoreTrackingHandler(orderRepository, shipmentRepository)
	storeTrackingDeps := &StoreTrackingDeps{
		Config:  cfg,
		Handler: trackingHandler,
	}
	return storeTrackingDeps, nil
}

// InitializeStoreProfileDeps creates Store Profile Lambda dependencies
func InitializeStoreProfileDeps(ctx context.Context, cfg *config.Config) (*StoreProfileDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	customerRepository := ProvideCustomerRepository(client)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	profileHandler := ProvideStoreProfileHandler(customerRepository, validation)
	otpRepository := ProvideOTPRepository(client)
	customerTokenStore := ProvideCustomerTokenStore(client)
	customerAuthService := ProvideCustomerAuthService(otpRepository, customerRepository, customerTokenStore, cfg)
	customerAuth := ProvideCustomerAuthMiddleware(customerAuthService)
	storeProfileDeps := &StoreProfileDeps{
		Config:                 cfg,
		Handler:                profileHandler,
		CustomerAuthMiddleware: customerAuth,
	}
	return storeProfileDeps, nil
}

// InitializeStoreWebhooksDeps creates Store Webhooks Lambda dependencies
func InitializeStoreWebhooksDeps(ctx context.Context, cfg *config.Config) (*StoreWebhooksDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	paymentRepository := ProvidePaymentRepository(client)
	orderRepository := ProvideOrderRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	inventoryRepository := ProvideInventoryRepository(pool)
	cartRepository := ProvideCartRepository(client)
	productRepository := ProvideProductRepository(pool)
	cartService := ProvideCartService(cartRepository, productRepository, inventoryRepository)
	customerRepository := ProvideCustomerRepository(client)
	gateway, err := ProvidePhonePeGateway(cfg)
	if err != nil {
		return nil, err
	}
	paymentService := ProvidePaymentService(paymentRepository, orderRepository, inventoryRepository, cartService, customerRepository, gateway)
	refundRepository := ProvideRefundRepository(client)
	notificationRepository := ProvideNotificationRepository(client)
	userRepository := ProvideUserRepository(client)
	notificationService := ProvideNotificationService(notificationRepository, userRepository)
	refundService := ProvideStoreRefundService(refundRepository, orderRepository, paymentRepository, inventoryRepository, notificationService, gateway)
	webhookHandler := ProvideStoreWebhookHandler(paymentService, refundService, gateway, cfg)
	storeWebhooksDeps := &StoreWebhooksDeps{
		Config:  cfg,
		Handler: webhookHandler,
	}
	return storeWebhooksDeps, nil
}

// InitializeStoreEventsDeps creates Store Events Lambda dependencies.
// Needs PG for lazy-upsert into city_centroids on first sighting of a
// (city, country) pair. Metric counters themselves still flow via the
// SQS publisher initialised in bootstrap.
func InitializeStoreEventsDeps(ctx context.Context, cfg *config.Config) (*StoreEventsDeps, error) {
	service := ProvideValidator()
	validation := ProvideValidation(service)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	centroidsRepository := ProvideCentroidsRepository(pool)
	eventsHandler := ProvideStoreEventsHandler(validation, centroidsRepository)
	storeEventsDeps := &StoreEventsDeps{
		Config:  cfg,
		Handler: eventsHandler,
	}
	return storeEventsDeps, nil
}

// InitializeMonolithDeps wires the full monolith dependency graph.
func InitializeMonolithDeps(ctx context.Context, cfg *config.Config) (*MonolithDeps, error) {
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	userService := ProvideUserService(userRepository, tokenStore)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	authHandler := ProvideAuthHandler(authService, userService, validation)
	userHandler := ProvideUserHandler(userService, validation)
	categoryRepository := ProvideCategoryRepository(pool)
	productRepository := ProvideProductRepository(pool)
	s3Client, err := ProvideS3Client(ctx, cfg)
	if err != nil {
		return nil, err
	}
	lambdaClient, err := ProvideLambdaClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	assetService := ProvideAssetService(s3Client, lambdaClient, cfg)
	categoryService := ProvideCategoryService(categoryRepository, productRepository, assetService)
	categoryHandler := ProvideCategoryHandler(categoryService, validation)
	inventoryRepository := ProvideInventoryRepository(pool)
	embedderClient, err := ProvideEmbedderClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	productService := ProvideProductService(productRepository, categoryRepository, inventoryRepository, assetService, embedderClient)
	inventoryService := ProvideInventoryService(inventoryRepository, userRepository)
	productHandler := ProvideProductHandler(productService, inventoryService, validation)
	inventoryHandler := ProvideInventoryHandler(inventoryService)
	pricingRuleRepository := ProvidePricingRuleRepository(client)
	priceQuoteRepository := ProvidePriceQuoteRepository(client)
	pricingService := ProvidePricingService(pricingRuleRepository, priceQuoteRepository, categoryRepository, productRepository, cfg)
	pricingHandler := ProvidePricingHandler(pricingService, validation)
	orderRepository := ProvideOrderRepository(client)
	customerRepository := ProvideCustomerRepository(client)
	paymentRepository := ProvidePaymentRepository(client)
	orderService := ProvideOrderService(orderRepository, customerRepository, productRepository, inventoryRepository, priceQuoteRepository, paymentRepository, pricingService)
	cartRepository := ProvideCartRepository(client)
	cartService := ProvideCartService(cartRepository, productRepository, inventoryRepository)
	gateway, err := ProvidePhonePeGateway(cfg)
	if err != nil {
		return nil, err
	}
	paymentService := ProvidePaymentService(paymentRepository, orderRepository, inventoryRepository, cartService, customerRepository, gateway)
	refundRepository := ProvideRefundRepository(client)
	auditRepository := ProvideAuditRepository(client)
	auditService := ProvideAuditService(auditRepository)
	notificationRepository := ProvideNotificationRepository(client)
	notificationService := ProvideNotificationService(notificationRepository, userRepository)
	refundService := ProvideRefundService(refundRepository, orderRepository, paymentRepository, inventoryRepository, userRepository, auditService, notificationService, gateway)
	orderHandler := ProvideOrderHandler(orderService, paymentService, refundService, validation)
	customerService := ProvideCustomerService(customerRepository, orderRepository)
	customerHandler := ProvideCustomerHandler(customerService, validation)
	auditHandler := ProvideAuditHandler(auditService)
	notificationHandler := ProvideNotificationHandler(notificationService, validation)
	couponRepository := ProvideCouponRepository(client)
	couponService := ProvideCouponService(couponRepository)
	couponHandler := ProvideCouponHandler(couponService, validation)
	assetHandler := ProvideAssetHandler(assetService, validation)
	reportRepository := ProvideReportRepository(client)
	reportService := ProvideReportService(reportRepository, orderService, productService, customerService, inventoryService)
	reportHandler := ProvideReportHandler(reportService, validation)
	otpRepository := ProvideOTPRepository(client)
	customerTokenStore := ProvideCustomerTokenStore(client)
	customerAuthService := ProvideCustomerAuthService(otpRepository, customerRepository, customerTokenStore, cfg)
	storeAuthHandler := ProvideStoreAuthHandler(customerAuthService, cartService, validation)
	catalogHandler := ProvideStoreCatalogHandler(productService, categoryService, inventoryService)
	cartHandler := ProvideStoreCartHandler(cartService, validation)
	checkoutService := ProvideCheckoutService(cartService, orderRepository, paymentService, inventoryRepository, customerRepository)
	checkoutHandler := ProvideStoreCheckoutHandler(checkoutService, validation)
	storeOrderHandler := ProvideStoreOrderHandler(orderService, orderRepository)
	shipmentRepository := ProvideShipmentRepository(client)
	trackingHandler := ProvideStoreTrackingHandler(orderRepository, shipmentRepository)
	profileHandler := ProvideStoreProfileHandler(customerRepository, validation)
	webhookHandler := ProvideStoreWebhookHandler(paymentService, refundService, gateway, cfg)
	centroidsRepository := ProvideCentroidsRepository(pool)
	eventsHandler := ProvideStoreEventsHandler(validation, centroidsRepository)
	auth := ProvideAuthMiddleware(authService)
	customerAuth := ProvideCustomerAuthMiddleware(customerAuthService)
	optionalCartAuth := ProvideOptionalCartAuth(customerAuthService)
	monolithDeps := &MonolithDeps{
		PostgresPool:           pool,
		AuthHandler:            authHandler,
		UserHandler:            userHandler,
		CategoryHandler:        categoryHandler,
		ProductHandler:         productHandler,
		InventoryHandler:       inventoryHandler,
		PricingHandler:         pricingHandler,
		OrderHandler:           orderHandler,
		CustomerHandler:        customerHandler,
		AuditHandler:           auditHandler,
		NotificationHandler:    notificationHandler,
		CouponHandler:          couponHandler,
		AssetHandler:           assetHandler,
		ReportHandler:          reportHandler,
		StoreAuthHandler:       storeAuthHandler,
		StoreCatalogHandler:    catalogHandler,
		StoreCartHandler:       cartHandler,
		StoreCheckoutHandler:   checkoutHandler,
		StoreOrderHandler:      storeOrderHandler,
		StoreTrackingHandler:   trackingHandler,
		StoreProfileHandler:    profileHandler,
		StoreWebhookHandler:    webhookHandler,
		StoreEventsHandler:     eventsHandler,
		AuthMiddleware:         auth,
		CustomerAuthMiddleware: customerAuth,
		OptionalCartAuth:       optionalCartAuth,
	}
	return monolithDeps, nil
}

// InitializeBackfillDeps creates the backfill Lambda dependencies.
func InitializeBackfillDeps(ctx context.Context, cfg *config.Config) (*BackfillDeps, error) {
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	client, err := ProvideEmbedderClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	backfillDeps := &BackfillDeps{
		Config:         cfg,
		Pool:           pool,
		EmbedderClient: client,
	}
	return backfillDeps, nil
}

// InitializeMetricsConsumerDeps creates the metrics consumer Lambda dependencies.
func InitializeMetricsConsumerDeps(ctx context.Context, cfg *config.Config) (*MetricsConsumerDeps, error) {
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	metricsRepository := ProvideMetricsRepository(pool)
	idempotencyCache := ProvideIdempotencyCache()
	handler := ProvideMetricsConsumerHandler(metricsRepository, idempotencyCache)
	metricsConsumerDeps := &MetricsConsumerDeps{
		Handler: handler,
	}
	return metricsConsumerDeps, nil
}

// wire.go:

// AuthDeps holds dependencies for the Auth Lambda
type AuthDeps struct {
	Config         *config.Config
	Handler        *handler.AuthHandler
	AuthMiddleware *middleware.Auth
}

// UserDeps holds dependencies for the User Lambda
type UserDeps struct {
	Config         *config.Config
	Handler        *handler.UserHandler
	AuthMiddleware *middleware.Auth
}

// CatalogDeps holds dependencies for the Catalog Lambda
type CatalogDeps struct {
	Config          *config.Config
	CategoryHandler *handler.CategoryHandler
	ProductHandler  *handler.ProductHandler
	AuthMiddleware  *middleware.Auth
	EmbedderClient  *embedder.Client
}

// OrderDeps holds dependencies for the Order Lambda
type OrderDeps struct {
	Config          *config.Config
	OrderHandler    *handler.OrderHandler
	CustomerHandler *handler.CustomerHandler
	AuthMiddleware  *middleware.Auth
}

// PricingDeps holds dependencies for the Pricing Lambda
type PricingDeps struct {
	Config         *config.Config
	Handler        *handler.PricingHandler
	AuthMiddleware *middleware.Auth
}

// InventoryDeps holds dependencies for the Inventory Lambda
type InventoryDeps struct {
	Config         *config.Config
	Handler        *handler.InventoryHandler
	AuthMiddleware *middleware.Auth
}

// NotificationDeps holds dependencies for the Notification Lambda
type NotificationDeps struct {
	Config         *config.Config
	Handler        *handler.NotificationHandler
	AuthMiddleware *middleware.Auth
}

// CouponDeps holds dependencies for the Coupon Lambda
type CouponDeps struct {
	Config         *config.Config
	Handler        *handler.CouponHandler
	AuthMiddleware *middleware.Auth
}

// AssetDeps holds dependencies for the Asset Lambda
type AssetDeps struct {
	Config         *config.Config
	Handler        *handler.AssetHandler
	AuthMiddleware *middleware.Auth
}

// ReportDeps holds dependencies for the Report Lambda
type ReportDeps struct {
	Config         *config.Config
	Handler        *handler.ReportHandler
	AuthMiddleware *middleware.Auth
}

// AuditDeps holds dependencies for the Audit Lambda
type AuditDeps struct {
	Config         *config.Config
	Handler        *handler.AuditHandler
	AuthMiddleware *middleware.Auth
}

// StoreAuthDeps holds dependencies for the Store Auth Lambda
type StoreAuthDeps struct {
	Config                 *config.Config
	Handler                *store.AuthHandler
	CustomerAuthMiddleware *middleware.CustomerAuth
}

// StoreCatalogDeps holds dependencies for the Store Catalog Lambda
type StoreCatalogDeps struct {
	Config  *config.Config
	Handler *store.CatalogHandler
}

// StoreCartDeps holds dependencies for the Store Cart Lambda
type StoreCartDeps struct {
	Config           *config.Config
	Handler          *store.CartHandler
	OptionalCartAuth *middleware.OptionalCartAuth
}

// StoreCheckoutDeps holds dependencies for the Store Checkout Lambda
type StoreCheckoutDeps struct {
	Config                 *config.Config
	Handler                *store.CheckoutHandler
	CustomerAuthMiddleware *middleware.CustomerAuth
}

// StoreOrdersDeps holds dependencies for the Store Orders Lambda
type StoreOrdersDeps struct {
	Config                 *config.Config
	Handler                *store.OrderHandler
	CustomerAuthMiddleware *middleware.CustomerAuth
}

// StoreTrackingDeps holds dependencies for the Store Tracking Lambda
type StoreTrackingDeps struct {
	Config  *config.Config
	Handler *store.TrackingHandler
}

// StoreProfileDeps holds dependencies for the Store Profile Lambda
type StoreProfileDeps struct {
	Config                 *config.Config
	Handler                *store.ProfileHandler
	CustomerAuthMiddleware *middleware.CustomerAuth
}

// StoreWebhooksDeps holds dependencies for the Store Webhooks Lambda
type StoreWebhooksDeps struct {
	Config  *config.Config
	Handler *store.WebhookHandler
}

// StoreEventsDeps holds dependencies for the Store Events Lambda
type StoreEventsDeps struct {
	Config  *config.Config
	Handler *store.EventsHandler
}

// MonolithDeps contains every dependency the monolith API server needs.
type MonolithDeps struct {
	// PostgresPool retained for graceful shutdown — DynamoDB SDK v2 needs none.
	PostgresPool *pgxpool.Pool

	// Admin handlers
	AuthHandler         *handler.AuthHandler
	UserHandler         *handler.UserHandler
	CategoryHandler     *handler.CategoryHandler
	ProductHandler      *handler.ProductHandler
	InventoryHandler    *handler.InventoryHandler
	PricingHandler      *handler.PricingHandler
	OrderHandler        *handler.OrderHandler
	CustomerHandler     *handler.CustomerHandler
	AuditHandler        *handler.AuditHandler
	NotificationHandler *handler.NotificationHandler
	CouponHandler       *handler.CouponHandler

	AssetHandler  *handler.AssetHandler
	ReportHandler *handler.ReportHandler

	// Store handlers
	StoreAuthHandler     *store.AuthHandler
	StoreCatalogHandler  *store.CatalogHandler
	StoreCartHandler     *store.CartHandler
	StoreCheckoutHandler *store.CheckoutHandler
	StoreOrderHandler    *store.OrderHandler
	StoreTrackingHandler *store.TrackingHandler
	StoreProfileHandler  *store.ProfileHandler
	StoreWebhookHandler  *store.WebhookHandler
	StoreEventsHandler   *store.EventsHandler

	// Middleware
	AuthMiddleware         *middleware.Auth
	CustomerAuthMiddleware *middleware.CustomerAuth
	OptionalCartAuth       *middleware.OptionalCartAuth
}

// BackfillDeps holds the minimal dependencies needed by the backfill Lambda
// (T19) to iterate over all products and upsert their embeddings.
type BackfillDeps struct {
	Config         *config.Config
	Pool           *pgxpool.Pool
	EmbedderClient *embedder.Client
}

// MetricsConsumerDeps holds dependencies for the metrics consumer Lambda.
type MetricsConsumerDeps struct {
	Handler *metrics.Handler
}
