// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/handloom/admin/internal/config"
	"github.com/handloom/admin/internal/handler"
	"github.com/handloom/admin/internal/handler/store"
	"github.com/handloom/admin/internal/middleware"
	"github.com/handloom/admin/internal/repository/dynamodb"
)

// Injectors from wire.go:

// InitializeApiDeps creates all dependencies for the main API server
func InitializeApiDeps(ctx context.Context, cfg *config.Config) (*ApiDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	userService := ProvideUserService(userRepository, tokenStore)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	authHandler := ProvideAuthHandler(authService, userService, validation)
	userHandler := ProvideUserHandler(userService, validation)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	cache := ProvideCatalogCache()
	categoryRepository := ProvideCategoryRepository(pool, cache)
	productRepository := ProvideProductRepository(pool, cache)
	s3Client, err := ProvideS3Client(ctx, cfg)
	if err != nil {
		return nil, err
	}
	assetService := ProvideAssetService(s3Client, cfg)
	categoryService := ProvideCategoryService(categoryRepository, productRepository, assetService)
	categoryHandler := ProvideCategoryHandler(categoryService, validation)
	inventoryRepository := ProvideInventoryRepository(pool)
	eventPublisher, err := ProvideEventPublisher(ctx, cfg)
	if err != nil {
		return nil, err
	}
	productService := ProvideProductService(productRepository, categoryRepository, inventoryRepository, assetService, eventPublisher)
	inventoryService := ProvideInventoryService(inventoryRepository, cache, eventPublisher)
	productHandler := ProvideProductHandler(productService, inventoryService, validation)
	inventoryHandler := ProvideInventoryHandler(inventoryService)
	pricingRuleRepository := ProvidePricingRuleRepository(client)
	priceQuoteRepository := ProvidePriceQuoteRepository(client)
	pricingService := ProvidePricingService(pricingRuleRepository, priceQuoteRepository, categoryRepository, productRepository, cfg)
	pricingHandler := ProvidePricingHandler(pricingService, validation)
	orderRepository := ProvideOrderRepository(client)
	customerRepository := ProvideCustomerRepository(client)
	orderService := ProvideOrderService(orderRepository, customerRepository, productRepository, inventoryRepository, priceQuoteRepository, pricingService)
	orderHandler := ProvideOrderHandler(orderService, validation)
	customerService := ProvideCustomerService(customerRepository, orderRepository)
	customerHandler := ProvideCustomerHandler(customerService, validation)
	auditRepository := ProvideAuditRepository(client)
	auditService := ProvideAuditService(auditRepository)
	auditHandler := ProvideAuditHandler(auditService)
	notificationRepository := ProvideNotificationRepository(client)
	notificationService := ProvideNotificationService(notificationRepository, userRepository)
	notificationHandler := ProvideNotificationHandler(notificationService, validation)
	couponRepository := ProvideCouponRepository(client)
	couponService := ProvideCouponService(couponRepository)
	couponHandler := ProvideCouponHandler(couponService, validation)
	analyticsRepository := ProvideAnalyticsRepository(client)
	analyticsService := ProvideAnalyticsService(analyticsRepository, orderRepository, productRepository, inventoryRepository)
	analyticsHandler := ProvideAnalyticsHandler(analyticsService)
	assetHandler := ProvideAssetHandler(assetService, validation)
	reportRepository := ProvideReportRepository(client)
	reportService := ProvideReportService(reportRepository, orderService, productService, customerService, inventoryService, analyticsService)
	reportHandler := ProvideReportHandler(reportService, validation)
	auth := ProvideAuthMiddleware(authService)
	apiDeps := &ApiDeps{
		Config:              cfg,
		DynamoDBClient:      client,
		AuthHandler:         authHandler,
		UserHandler:         userHandler,
		CategoryHandler:     categoryHandler,
		ProductHandler:      productHandler,
		InventoryHandler:    inventoryHandler,
		PricingHandler:      pricingHandler,
		OrderHandler:        orderHandler,
		CustomerHandler:     customerHandler,
		AuditHandler:        auditHandler,
		NotificationHandler: notificationHandler,
		CouponHandler:       couponHandler,
		AnalyticsHandler:    analyticsHandler,
		AssetHandler:        assetHandler,
		ReportHandler:       reportHandler,
		AuthMiddleware:      auth,
	}
	return apiDeps, nil
}

// InitializeAuthDeps creates Auth Lambda dependencies
func InitializeAuthDeps(ctx context.Context, cfg *config.Config) (*AuthDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	userService := ProvideUserService(userRepository, tokenStore)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	authHandler := ProvideAuthHandler(authService, userService, validation)
	auth := ProvideAuthMiddleware(authService)
	authDeps := &AuthDeps{
		Config:         cfg,
		Handler:        authHandler,
		AuthMiddleware: auth,
	}
	return authDeps, nil
}

// InitializeUserDeps creates User Lambda dependencies
func InitializeUserDeps(ctx context.Context, cfg *config.Config) (*UserDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	userService := ProvideUserService(userRepository, tokenStore)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	userHandler := ProvideUserHandler(userService, validation)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	userDeps := &UserDeps{
		Config:         cfg,
		Handler:        userHandler,
		AuthMiddleware: auth,
	}
	return userDeps, nil
}

// InitializeCatalogDeps creates Catalog Lambda dependencies
func InitializeCatalogDeps(ctx context.Context, cfg *config.Config) (*CatalogDeps, error) {
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	cache := ProvideCatalogCache()
	categoryRepository := ProvideCategoryRepository(pool, cache)
	productRepository := ProvideProductRepository(pool, cache)
	s3Client, err := ProvideS3Client(ctx, cfg)
	if err != nil {
		return nil, err
	}
	assetService := ProvideAssetService(s3Client, cfg)
	categoryService := ProvideCategoryService(categoryRepository, productRepository, assetService)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	categoryHandler := ProvideCategoryHandler(categoryService, validation)
	inventoryRepository := ProvideInventoryRepository(pool)
	eventPublisher, err := ProvideEventPublisher(ctx, cfg)
	if err != nil {
		return nil, err
	}
	productService := ProvideProductService(productRepository, categoryRepository, inventoryRepository, assetService, eventPublisher)
	inventoryService := ProvideInventoryService(inventoryRepository, cache, eventPublisher)
	productHandler := ProvideProductHandler(productService, inventoryService, validation)
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	catalogDeps := &CatalogDeps{
		Config:          cfg,
		CategoryHandler: categoryHandler,
		ProductHandler:  productHandler,
		AuthMiddleware:  auth,
	}
	return catalogDeps, nil
}

// InitializeOrderDeps creates Order Lambda dependencies
func InitializeOrderDeps(ctx context.Context, cfg *config.Config) (*OrderDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	orderRepository := ProvideOrderRepository(client)
	customerRepository := ProvideCustomerRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	cache := ProvideCatalogCache()
	productRepository := ProvideProductRepository(pool, cache)
	inventoryRepository := ProvideInventoryRepository(pool)
	priceQuoteRepository := ProvidePriceQuoteRepository(client)
	pricingRuleRepository := ProvidePricingRuleRepository(client)
	categoryRepository := ProvideCategoryRepository(pool, cache)
	pricingService := ProvidePricingService(pricingRuleRepository, priceQuoteRepository, categoryRepository, productRepository, cfg)
	orderService := ProvideOrderService(orderRepository, customerRepository, productRepository, inventoryRepository, priceQuoteRepository, pricingService)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	orderHandler := ProvideOrderHandler(orderService, validation)
	customerService := ProvideCustomerService(customerRepository, orderRepository)
	customerHandler := ProvideCustomerHandler(customerService, validation)
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	orderDeps := &OrderDeps{
		Config:          cfg,
		OrderHandler:    orderHandler,
		CustomerHandler: customerHandler,
		AuthMiddleware:  auth,
	}
	return orderDeps, nil
}

// InitializePricingDeps creates Pricing Lambda dependencies
func InitializePricingDeps(ctx context.Context, cfg *config.Config) (*PricingDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	pricingRuleRepository := ProvidePricingRuleRepository(client)
	priceQuoteRepository := ProvidePriceQuoteRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	cache := ProvideCatalogCache()
	categoryRepository := ProvideCategoryRepository(pool, cache)
	productRepository := ProvideProductRepository(pool, cache)
	pricingService := ProvidePricingService(pricingRuleRepository, priceQuoteRepository, categoryRepository, productRepository, cfg)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	pricingHandler := ProvidePricingHandler(pricingService, validation)
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	pricingDeps := &PricingDeps{
		Config:         cfg,
		Handler:        pricingHandler,
		AuthMiddleware: auth,
	}
	return pricingDeps, nil
}

// InitializeInventoryDeps creates Inventory Lambda dependencies
func InitializeInventoryDeps(ctx context.Context, cfg *config.Config) (*InventoryDeps, error) {
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	inventoryRepository := ProvideInventoryRepository(pool)
	cache := ProvideCatalogCache()
	eventPublisher, err := ProvideEventPublisher(ctx, cfg)
	if err != nil {
		return nil, err
	}
	inventoryService := ProvideInventoryService(inventoryRepository, cache, eventPublisher)
	inventoryHandler := ProvideInventoryHandler(inventoryService)
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	inventoryDeps := &InventoryDeps{
		Config:         cfg,
		Handler:        inventoryHandler,
		AuthMiddleware: auth,
	}
	return inventoryDeps, nil
}

// InitializeAnalyticsDeps creates Analytics Lambda dependencies
func InitializeAnalyticsDeps(ctx context.Context, cfg *config.Config) (*AnalyticsDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	analyticsRepository := ProvideAnalyticsRepository(client)
	orderRepository := ProvideOrderRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	cache := ProvideCatalogCache()
	productRepository := ProvideProductRepository(pool, cache)
	inventoryRepository := ProvideInventoryRepository(pool)
	analyticsService := ProvideAnalyticsService(analyticsRepository, orderRepository, productRepository, inventoryRepository)
	analyticsHandler := ProvideAnalyticsHandler(analyticsService)
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	analyticsDeps := &AnalyticsDeps{
		Config:         cfg,
		Handler:        analyticsHandler,
		AuthMiddleware: auth,
	}
	return analyticsDeps, nil
}

// InitializeNotificationDeps creates Notification Lambda dependencies
func InitializeNotificationDeps(ctx context.Context, cfg *config.Config) (*NotificationDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	notificationRepository := ProvideNotificationRepository(client)
	userRepository := ProvideUserRepository(client)
	notificationService := ProvideNotificationService(notificationRepository, userRepository)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	notificationHandler := ProvideNotificationHandler(notificationService, validation)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	notificationDeps := &NotificationDeps{
		Config:         cfg,
		Handler:        notificationHandler,
		AuthMiddleware: auth,
	}
	return notificationDeps, nil
}

// InitializeCouponDeps creates Coupon Lambda dependencies
func InitializeCouponDeps(ctx context.Context, cfg *config.Config) (*CouponDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	couponRepository := ProvideCouponRepository(client)
	couponService := ProvideCouponService(couponRepository)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	couponHandler := ProvideCouponHandler(couponService, validation)
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	couponDeps := &CouponDeps{
		Config:         cfg,
		Handler:        couponHandler,
		AuthMiddleware: auth,
	}
	return couponDeps, nil
}

// InitializeAssetDeps creates Asset Lambda dependencies
func InitializeAssetDeps(ctx context.Context, cfg *config.Config) (*AssetDeps, error) {
	s3Client, err := ProvideS3Client(ctx, cfg)
	if err != nil {
		return nil, err
	}
	assetService := ProvideAssetService(s3Client, cfg)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	assetHandler := ProvideAssetHandler(assetService, validation)
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	assetDeps := &AssetDeps{
		Config:         cfg,
		Handler:        assetHandler,
		AuthMiddleware: auth,
	}
	return assetDeps, nil
}

// InitializeReportDeps creates Report Lambda dependencies
func InitializeReportDeps(ctx context.Context, cfg *config.Config) (*ReportDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	reportRepository := ProvideReportRepository(client)
	orderRepository := ProvideOrderRepository(client)
	customerRepository := ProvideCustomerRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	cache := ProvideCatalogCache()
	productRepository := ProvideProductRepository(pool, cache)
	inventoryRepository := ProvideInventoryRepository(pool)
	priceQuoteRepository := ProvidePriceQuoteRepository(client)
	pricingRuleRepository := ProvidePricingRuleRepository(client)
	categoryRepository := ProvideCategoryRepository(pool, cache)
	pricingService := ProvidePricingService(pricingRuleRepository, priceQuoteRepository, categoryRepository, productRepository, cfg)
	orderService := ProvideOrderService(orderRepository, customerRepository, productRepository, inventoryRepository, priceQuoteRepository, pricingService)
	s3Client, err := ProvideS3Client(ctx, cfg)
	if err != nil {
		return nil, err
	}
	assetService := ProvideAssetService(s3Client, cfg)
	eventPublisher, err := ProvideEventPublisher(ctx, cfg)
	if err != nil {
		return nil, err
	}
	productService := ProvideProductService(productRepository, categoryRepository, inventoryRepository, assetService, eventPublisher)
	customerService := ProvideCustomerService(customerRepository, orderRepository)
	inventoryService := ProvideInventoryService(inventoryRepository, cache, eventPublisher)
	analyticsRepository := ProvideAnalyticsRepository(client)
	analyticsService := ProvideAnalyticsService(analyticsRepository, orderRepository, productRepository, inventoryRepository)
	reportService := ProvideReportService(reportRepository, orderService, productService, customerService, inventoryService, analyticsService)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	reportHandler := ProvideReportHandler(reportService, validation)
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	reportDeps := &ReportDeps{
		Config:         cfg,
		Handler:        reportHandler,
		AuthMiddleware: auth,
	}
	return reportDeps, nil
}

// InitializeAuditDeps creates Audit Lambda dependencies
func InitializeAuditDeps(ctx context.Context, cfg *config.Config) (*AuditDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	auditRepository := ProvideAuditRepository(client)
	auditService := ProvideAuditService(auditRepository)
	auditHandler := ProvideAuditHandler(auditService)
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	auditDeps := &AuditDeps{
		Config:         cfg,
		Handler:        auditHandler,
		AuthMiddleware: auth,
	}
	return auditDeps, nil
}

// InitializeStoreAuthDeps creates Store Auth Lambda dependencies
func InitializeStoreAuthDeps(ctx context.Context, cfg *config.Config) (*StoreAuthDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	otpRepository := ProvideOTPRepository(client)
	customerRepository := ProvideCustomerRepository(client)
	customerTokenStore := ProvideCustomerTokenStore(client)
	eventPublisher, err := ProvideEventPublisher(ctx, cfg)
	if err != nil {
		return nil, err
	}
	customerAuthService := ProvideCustomerAuthService(otpRepository, customerRepository, customerTokenStore, eventPublisher, cfg)
	cartRepository := ProvideCartRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	cache := ProvideCatalogCache()
	productRepository := ProvideProductRepository(pool, cache)
	inventoryRepository := ProvideInventoryRepository(pool)
	cartService := ProvideCartService(cartRepository, productRepository, inventoryRepository)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	authHandler := ProvideStoreAuthHandler(customerAuthService, cartService, validation)
	customerAuth := ProvideCustomerAuthMiddleware(customerAuthService)
	storeAuthDeps := &StoreAuthDeps{
		Config:                 cfg,
		Handler:                authHandler,
		CustomerAuthMiddleware: customerAuth,
	}
	return storeAuthDeps, nil
}

// InitializeStoreCatalogDeps creates Store Catalog Lambda dependencies
func InitializeStoreCatalogDeps(ctx context.Context, cfg *config.Config) (*StoreCatalogDeps, error) {
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	cache := ProvideCatalogCache()
	productRepository := ProvideProductRepository(pool, cache)
	categoryRepository := ProvideCategoryRepository(pool, cache)
	inventoryRepository := ProvideInventoryRepository(pool)
	s3Client, err := ProvideS3Client(ctx, cfg)
	if err != nil {
		return nil, err
	}
	assetService := ProvideAssetService(s3Client, cfg)
	eventPublisher, err := ProvideEventPublisher(ctx, cfg)
	if err != nil {
		return nil, err
	}
	productService := ProvideProductService(productRepository, categoryRepository, inventoryRepository, assetService, eventPublisher)
	categoryService := ProvideCategoryService(categoryRepository, productRepository, assetService)
	inventoryService := ProvideInventoryService(inventoryRepository, cache, eventPublisher)
	catalogHandler := ProvideStoreCatalogHandler(productService, categoryService, inventoryService)
	storeCatalogDeps := &StoreCatalogDeps{
		Config:  cfg,
		Handler: catalogHandler,
	}
	return storeCatalogDeps, nil
}

// InitializeStoreCartDeps creates Store Cart Lambda dependencies
func InitializeStoreCartDeps(ctx context.Context, cfg *config.Config) (*StoreCartDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	cartRepository := ProvideCartRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	cache := ProvideCatalogCache()
	productRepository := ProvideProductRepository(pool, cache)
	inventoryRepository := ProvideInventoryRepository(pool)
	cartService := ProvideCartService(cartRepository, productRepository, inventoryRepository)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	cartHandler := ProvideStoreCartHandler(cartService, validation)
	otpRepository := ProvideOTPRepository(client)
	customerRepository := ProvideCustomerRepository(client)
	customerTokenStore := ProvideCustomerTokenStore(client)
	eventPublisher, err := ProvideEventPublisher(ctx, cfg)
	if err != nil {
		return nil, err
	}
	customerAuthService := ProvideCustomerAuthService(otpRepository, customerRepository, customerTokenStore, eventPublisher, cfg)
	optionalCartAuth := ProvideOptionalCartAuth(customerAuthService)
	storeCartDeps := &StoreCartDeps{
		Config:           cfg,
		Handler:          cartHandler,
		OptionalCartAuth: optionalCartAuth,
	}
	return storeCartDeps, nil
}

// InitializeStoreCheckoutDeps creates Store Checkout Lambda dependencies
func InitializeStoreCheckoutDeps(ctx context.Context, cfg *config.Config) (*StoreCheckoutDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	cartRepository := ProvideCartRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	cache := ProvideCatalogCache()
	productRepository := ProvideProductRepository(pool, cache)
	inventoryRepository := ProvideInventoryRepository(pool)
	cartService := ProvideCartService(cartRepository, productRepository, inventoryRepository)
	orderRepository := ProvideOrderRepository(client)
	paymentRepository := ProvidePaymentRepository(client)
	eventPublisher, err := ProvideEventPublisher(ctx, cfg)
	if err != nil {
		return nil, err
	}
	paymentService := ProvidePaymentService(paymentRepository, orderRepository, inventoryRepository, eventPublisher, cfg)
	shipmentRepository := ProvideShipmentRepository(client)
	shippingService := ProvideShippingService(shipmentRepository, orderRepository, cfg)
	customerRepository := ProvideCustomerRepository(client)
	checkoutService := ProvideCheckoutService(cartService, orderRepository, paymentService, shippingService, inventoryRepository, customerRepository, eventPublisher)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	checkoutHandler := ProvideStoreCheckoutHandler(checkoutService, validation)
	otpRepository := ProvideOTPRepository(client)
	customerTokenStore := ProvideCustomerTokenStore(client)
	customerAuthService := ProvideCustomerAuthService(otpRepository, customerRepository, customerTokenStore, eventPublisher, cfg)
	customerAuth := ProvideCustomerAuthMiddleware(customerAuthService)
	storeCheckoutDeps := &StoreCheckoutDeps{
		Config:                 cfg,
		Handler:                checkoutHandler,
		CustomerAuthMiddleware: customerAuth,
	}
	return storeCheckoutDeps, nil
}

// InitializeStoreOrdersDeps creates Store Orders Lambda dependencies
func InitializeStoreOrdersDeps(ctx context.Context, cfg *config.Config) (*StoreOrdersDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	orderRepository := ProvideOrderRepository(client)
	customerRepository := ProvideCustomerRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	cache := ProvideCatalogCache()
	productRepository := ProvideProductRepository(pool, cache)
	inventoryRepository := ProvideInventoryRepository(pool)
	priceQuoteRepository := ProvidePriceQuoteRepository(client)
	pricingRuleRepository := ProvidePricingRuleRepository(client)
	categoryRepository := ProvideCategoryRepository(pool, cache)
	pricingService := ProvidePricingService(pricingRuleRepository, priceQuoteRepository, categoryRepository, productRepository, cfg)
	orderService := ProvideOrderService(orderRepository, customerRepository, productRepository, inventoryRepository, priceQuoteRepository, pricingService)
	orderHandler := ProvideStoreOrderHandler(orderService, orderRepository)
	otpRepository := ProvideOTPRepository(client)
	customerTokenStore := ProvideCustomerTokenStore(client)
	eventPublisher, err := ProvideEventPublisher(ctx, cfg)
	if err != nil {
		return nil, err
	}
	customerAuthService := ProvideCustomerAuthService(otpRepository, customerRepository, customerTokenStore, eventPublisher, cfg)
	customerAuth := ProvideCustomerAuthMiddleware(customerAuthService)
	storeOrdersDeps := &StoreOrdersDeps{
		Config:                 cfg,
		Handler:                orderHandler,
		CustomerAuthMiddleware: customerAuth,
	}
	return storeOrdersDeps, nil
}

// InitializeStoreTrackingDeps creates Store Tracking Lambda dependencies
func InitializeStoreTrackingDeps(ctx context.Context, cfg *config.Config) (*StoreTrackingDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	orderRepository := ProvideOrderRepository(client)
	shipmentRepository := ProvideShipmentRepository(client)
	trackingHandler := ProvideStoreTrackingHandler(orderRepository, shipmentRepository)
	storeTrackingDeps := &StoreTrackingDeps{
		Config:  cfg,
		Handler: trackingHandler,
	}
	return storeTrackingDeps, nil
}

// InitializeStoreProfileDeps creates Store Profile Lambda dependencies
func InitializeStoreProfileDeps(ctx context.Context, cfg *config.Config) (*StoreProfileDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	customerRepository := ProvideCustomerRepository(client)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	profileHandler := ProvideStoreProfileHandler(customerRepository, validation)
	otpRepository := ProvideOTPRepository(client)
	customerTokenStore := ProvideCustomerTokenStore(client)
	eventPublisher, err := ProvideEventPublisher(ctx, cfg)
	if err != nil {
		return nil, err
	}
	customerAuthService := ProvideCustomerAuthService(otpRepository, customerRepository, customerTokenStore, eventPublisher, cfg)
	customerAuth := ProvideCustomerAuthMiddleware(customerAuthService)
	storeProfileDeps := &StoreProfileDeps{
		Config:                 cfg,
		Handler:                profileHandler,
		CustomerAuthMiddleware: customerAuth,
	}
	return storeProfileDeps, nil
}

// InitializeStoreWebhooksDeps creates Store Webhooks Lambda dependencies
func InitializeStoreWebhooksDeps(ctx context.Context, cfg *config.Config) (*StoreWebhooksDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	paymentRepository := ProvidePaymentRepository(client)
	orderRepository := ProvideOrderRepository(client)
	pool, err := ProvidePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	inventoryRepository := ProvideInventoryRepository(pool)
	eventPublisher, err := ProvideEventPublisher(ctx, cfg)
	if err != nil {
		return nil, err
	}
	paymentService := ProvidePaymentService(paymentRepository, orderRepository, inventoryRepository, eventPublisher, cfg)
	webhookHandler := ProvideStoreWebhookHandler(paymentService)
	storeWebhooksDeps := &StoreWebhooksDeps{
		Config:  cfg,
		Handler: webhookHandler,
	}
	return storeWebhooksDeps, nil
}

// InitializeStoreEventsDeps creates Store Events Lambda dependencies
func InitializeStoreEventsDeps(ctx context.Context, cfg *config.Config) (*StoreEventsDeps, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	eventsRepository := ProvideEventsRepository(client)
	analyticsRepository := ProvideAnalyticsRepository(client)
	service := ProvideValidator()
	validation := ProvideValidation(service)
	eventsHandler := ProvideStoreEventsHandler(eventsRepository, analyticsRepository, validation)
	storeEventsDeps := &StoreEventsDeps{
		Config:  cfg,
		Handler: eventsHandler,
	}
	return storeEventsDeps, nil
}

// InitializeApp creates the application with all dependencies (deprecated)
func InitializeApp(ctx context.Context, cfg *config.Config) (*App, error) {
	client, err := ProvideDynamoDBClient(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := ProvideUserRepository(client)
	tokenStore := ProvideTokenStore(client)
	authService := ProvideAuthService(userRepository, tokenStore, cfg)
	auth := ProvideAuthMiddleware(authService)
	app := &App{
		Config:         cfg,
		DynamoDBClient: client,
		AuthMiddleware: auth,
	}
	return app, nil
}

// wire.go:

// AuthDeps holds dependencies for the Auth Lambda
type AuthDeps struct {
	Config         *config.Config
	Handler        *handler.AuthHandler
	AuthMiddleware *middleware.Auth
}

// UserDeps holds dependencies for the User Lambda
type UserDeps struct {
	Config         *config.Config
	Handler        *handler.UserHandler
	AuthMiddleware *middleware.Auth
}

// CatalogDeps holds dependencies for the Catalog Lambda
type CatalogDeps struct {
	Config          *config.Config
	CategoryHandler *handler.CategoryHandler
	ProductHandler  *handler.ProductHandler
	AuthMiddleware  *middleware.Auth
}

// OrderDeps holds dependencies for the Order Lambda
type OrderDeps struct {
	Config          *config.Config
	OrderHandler    *handler.OrderHandler
	CustomerHandler *handler.CustomerHandler
	AuthMiddleware  *middleware.Auth
}

// PricingDeps holds dependencies for the Pricing Lambda
type PricingDeps struct {
	Config         *config.Config
	Handler        *handler.PricingHandler
	AuthMiddleware *middleware.Auth
}

// InventoryDeps holds dependencies for the Inventory Lambda
type InventoryDeps struct {
	Config         *config.Config
	Handler        *handler.InventoryHandler
	AuthMiddleware *middleware.Auth
}

// AnalyticsDeps holds dependencies for the Analytics Lambda
type AnalyticsDeps struct {
	Config         *config.Config
	Handler        *handler.AnalyticsHandler
	AuthMiddleware *middleware.Auth
}

// NotificationDeps holds dependencies for the Notification Lambda
type NotificationDeps struct {
	Config         *config.Config
	Handler        *handler.NotificationHandler
	AuthMiddleware *middleware.Auth
}

// CouponDeps holds dependencies for the Coupon Lambda
type CouponDeps struct {
	Config         *config.Config
	Handler        *handler.CouponHandler
	AuthMiddleware *middleware.Auth
}

// AssetDeps holds dependencies for the Asset Lambda
type AssetDeps struct {
	Config         *config.Config
	Handler        *handler.AssetHandler
	AuthMiddleware *middleware.Auth
}

// ReportDeps holds dependencies for the Report Lambda
type ReportDeps struct {
	Config         *config.Config
	Handler        *handler.ReportHandler
	AuthMiddleware *middleware.Auth
}

// AuditDeps holds dependencies for the Audit Lambda
type AuditDeps struct {
	Config         *config.Config
	Handler        *handler.AuditHandler
	AuthMiddleware *middleware.Auth
}

// ApiDeps holds all dependencies for the main API server
type ApiDeps struct {
	Config              *config.Config
	DynamoDBClient      *dynamodb.Client
	AuthHandler         *handler.AuthHandler
	UserHandler         *handler.UserHandler
	CategoryHandler     *handler.CategoryHandler
	ProductHandler      *handler.ProductHandler
	InventoryHandler    *handler.InventoryHandler
	PricingHandler      *handler.PricingHandler
	OrderHandler        *handler.OrderHandler
	CustomerHandler     *handler.CustomerHandler
	AuditHandler        *handler.AuditHandler
	NotificationHandler *handler.NotificationHandler
	CouponHandler       *handler.CouponHandler
	AnalyticsHandler    *handler.AnalyticsHandler
	AssetHandler        *handler.AssetHandler
	ReportHandler       *handler.ReportHandler
	AuthMiddleware      *middleware.Auth
}

// StoreAuthDeps holds dependencies for the Store Auth Lambda
type StoreAuthDeps struct {
	Config                 *config.Config
	Handler                *store.AuthHandler
	CustomerAuthMiddleware *middleware.CustomerAuth
}

// StoreCatalogDeps holds dependencies for the Store Catalog Lambda
type StoreCatalogDeps struct {
	Config  *config.Config
	Handler *store.CatalogHandler
}

// StoreCartDeps holds dependencies for the Store Cart Lambda
type StoreCartDeps struct {
	Config           *config.Config
	Handler          *store.CartHandler
	OptionalCartAuth *middleware.OptionalCartAuth
}

// StoreCheckoutDeps holds dependencies for the Store Checkout Lambda
type StoreCheckoutDeps struct {
	Config                 *config.Config
	Handler                *store.CheckoutHandler
	CustomerAuthMiddleware *middleware.CustomerAuth
}

// StoreOrdersDeps holds dependencies for the Store Orders Lambda
type StoreOrdersDeps struct {
	Config                 *config.Config
	Handler                *store.OrderHandler
	CustomerAuthMiddleware *middleware.CustomerAuth
}

// StoreTrackingDeps holds dependencies for the Store Tracking Lambda
type StoreTrackingDeps struct {
	Config  *config.Config
	Handler *store.TrackingHandler
}

// StoreProfileDeps holds dependencies for the Store Profile Lambda
type StoreProfileDeps struct {
	Config                 *config.Config
	Handler                *store.ProfileHandler
	CustomerAuthMiddleware *middleware.CustomerAuth
}

// StoreWebhooksDeps holds dependencies for the Store Webhooks Lambda
type StoreWebhooksDeps struct {
	Config  *config.Config
	Handler *store.WebhookHandler
}

// StoreEventsDeps holds dependencies for the Store Events Lambda
type StoreEventsDeps struct {
	Config  *config.Config
	Handler *store.EventsHandler
}

// App holds all application dependencies (deprecated, use service-specific deps)
type App struct {
	Config         *config.Config
	DynamoDBClient *dynamodb.Client
	AuthMiddleware *middleware.Auth
}
