// Command put-vapid-key provisions the Web Push (VAPID) signing key for one
// environment.
//
//	go run ./scripts/put-vapid-key local      # write a keypair into .env
//	go run ./scripts/put-vapid-key dev|prod   # private half to SSM, public half printed
//
// The push Lambda reads /handloom/{env}/vapid-private-key at runtime, and
// nothing creates that parameter, so it must exist before the stack is deployed.
//
// local is idempotent — it leaves an existing keypair alone, so `make run` can
// depend on it. dev and prod replace the key on every run: browsers bind their
// subscription to the key they subscribed with, so re-running against a live
// environment silently stops delivery to every existing subscriber.
package main

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	webpush "github.com/SherClockHolmes/webpush-go"
	"github.com/aws/aws-sdk-go-v2/aws"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/ssm"
	ssmtypes "github.com/aws/aws-sdk-go-v2/service/ssm/types"
)

const defaultRegion = "ap-south-1"

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "::error::%v\n", err)
		os.Exit(1)
	}
}

func run() error {
	if len(os.Args) != 2 {
		return fmt.Errorf("usage: put-vapid-key <local|dev|prod>")
	}
	env := os.Args[1]
	if env != "local" && env != "dev" && env != "prod" {
		return fmt.Errorf("usage: put-vapid-key <local|dev|prod>")
	}

	if env == "local" {
		return writeLocalEnv()
	}

	private, public, err := webpush.GenerateVAPIDKeys()
	if err != nil {
		return fmt.Errorf("could not generate a VAPID keypair: %w", err)
	}
	// Keep the private half out of any log this program or its caller produces.
	fmt.Printf("::add-mask::%s\n", private)

	region := os.Getenv("AWS_REGION")
	if region == "" {
		region = defaultRegion
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	cfg, err := awsconfig.LoadDefaultConfig(ctx, awsconfig.WithRegion(region))
	if err != nil {
		return fmt.Errorf("could not load AWS config: %w", err)
	}

	name := fmt.Sprintf("/handloom/%s/vapid-private-key", env)
	_, err = ssm.NewFromConfig(cfg).PutParameter(ctx, &ssm.PutParameterInput{
		Name:        aws.String(name),
		Value:       aws.String(private),
		Type:        ssmtypes.ParameterTypeSecureString,
		Description: aws.String(fmt.Sprintf("Web Push VAPID private key (%s) — read at runtime by the push Lambda", env)),
		Overwrite:   aws.Bool(true),
	})
	if err != nil {
		return fmt.Errorf("could not write %s: %w", name, err)
	}

	fmt.Printf("Wrote %s in %s.\n\n", name, region)
	fmt.Printf("Add these to the BACKEND_ENV_%s secret (neither is secret), then deploy:\n",
		strings.ToUpper(env))
	fmt.Printf("  VAPID_PUBLIC_KEY=%s\n", public)
	fmt.Println("  VAPID_SUBJECT=mailto:info@homechrome.in")
	return nil
}

// writeLocalEnv appends a keypair to .env for local development, leaving an
// existing one alone so this can be a prerequisite of every local target.
func writeLocalEnv() error {
	const path = ".env"

	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("could not read %s: %w", path, err)
	}
	for _, line := range strings.Split(string(existing), "\n") {
		if strings.HasPrefix(line, "VAPID_PRIVATE_KEY=") && len(line) > len("VAPID_PRIVATE_KEY=") {
			fmt.Println("VAPID keys present in .env")
			return nil
		}
	}

	private, public, err := webpush.GenerateVAPIDKeys()
	if err != nil {
		return fmt.Errorf("could not generate a VAPID keypair: %w", err)
	}

	block := fmt.Sprintf(
		"\n# Web Push (VAPID) — local only, generated by `make ensure-vapid`.\n"+
			"# Deployed environments get their own pair; never reuse these.\n"+
			"VAPID_PUBLIC_KEY=%s\nVAPID_PRIVATE_KEY=%s\nVAPID_SUBJECT=mailto:dev@homechrome.in\n",
		public, private)

	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)
	if err != nil {
		return fmt.Errorf("could not open %s: %w", path, err)
	}
	if _, err := f.WriteString(block); err != nil {
		_ = f.Close()
		return fmt.Errorf("could not write %s: %w", path, err)
	}
	// Checked, not deferred: a failed close here means the keys may not have
	// reached disk, and the caller would otherwise be told they had.
	if err := f.Close(); err != nil {
		return fmt.Errorf("could not finish writing %s: %w", path, err)
	}

	fmt.Println("VAPID keys written to .env (gitignored)")
	return nil
}
